#logging:
#  level:
#    ROOT: INFO
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG

#security:
#  oauth2:
#    sso:
#      home:
#        secure: false
#        path: /,/**/*.html
#    client:
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
#      clientId: acme
#      clientSecret: acmesecret
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user
